analytics: {}
color:
  brandColors:
    - '#A8C0D8'
    - '#304870'
    - '#507098'
    - '#5880B0'
    - '#C0D8E8'
  brandStrength: 0.439851
  lightness: 0.269087
  rhythmicContrast: 0.890346
  saturation: 0.038159
cta: {}
layout_spectrum: 0.226351
name: J Asher Consulting
opengraph: {}
purpose: {}
typography_spectrum: 1
