name: J Asher Consulting
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8C0D8'
    - '#304870'
    - '#507098'
    - '#5880B0'
    - '#C0D8E8'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.890346
purpose:
  - name: null
    item: null
    url: null
